version: '2.2'
services:
  stackstorm:
    image: solita/ubuntu-systemd
    container_name: stackstorm
    privileged: true
    cap_add:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ss:/usr/share/centos/data
    tty: true
    ports:
      - 443:443
    networks:
      - private

networks:
  public:
    driver: bridge
  private:
    driver: bridge

volumes:
  ss:
    driver: local
